part_2 (Django)/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

part_2 (Django)/quotes/urls.py
from django.urls import path, include
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('users/', include('users.urls')),
    path('quotes/create/', views.CreateQuoteView.as_view(), name='create_quote'),

]

part_2 (Django)/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [

    path('signup/', views.CustomSignupView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('authors/create/', views.CreateAuthorView.as_view(), name='create_author'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

part_2 (Django)/quotes/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

part_2 (Django)/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    # додайте поля за вашими потребами

    def __str__(self):
        return self.username

part_2 (Django)/quotes/views.py
from django.views.generic.edit import CreateView
from django.shortcuts import render
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin

from .utils import get_mongodb


def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


class QuoteCreateView(LoginRequiredMixin, CreateView):
    model = quotes
    fields = ['quote', 'tags', 'author']
    template_name = 'quotes/quote_form.html'
    success_url = reverse_lazy('quotes')

part_2 (Django)/users/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from allauth.account.views import SignupView
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin  # Додайте імпорт
from users.models import CustomUser


class HomePageView(LoginRequiredMixin, TemplateView):  # Використовуйте LoginRequiredMixin
    template_name = 'users/home.html'


class CustomLoginView(LoginView):
    template_name = 'users/login.html'


class CustomLogoutView(LogoutView):
    next_page = 'users:home'


class CustomSignupView(SignupView):
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:login')


class AuthorCreateView(LoginRequiredMixin, CreateView):
    model = author
    fields = ['fullname', 'born_date', 'born_location', 'description']
    template_name = 'users/author_form.html'
    success_url = reverse_lazy('authors')


class AuthorDetailView(DetailView):
    model = author
    template_name = 'users/author_detail.html'

part_2 (Django)/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body data-new-gr-c-s-check-loaded="14.1121.0" data-gr-ext-installed="">
    <div class="container">
        <div class="row header-box" pt-3>
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>

                <a href="{% url 'signup' %}" class="btn btn-info">Sign Up</a>
                <a href="{% url 'login' %}" class="btn btn-info">Login</a>
                <a href="{% url 'logout' %}" class="btn btn-info">Logout</a>


                </p>
            </div>
        </div>


        {% block content %} {% endblock %}

    </div>


</body>
</html>

part_2 (Django)/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.quote }}
            </span>
            <span>by <small class="author" itemprop="author">
                    {{ quote.author_id|author }} <!-- Виклик фільтра для отримання автора за його ID -->
                </small>
                <a href="/author/{{ quote.author_id }}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{ tag }}">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
            <ul class="pager">
                {% if quotes.has_previous %}
                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                            <span aria-hidden="true">←</span> Previous
                    </a>
                </li>
                {% endif %}
                {% if quotes.has_next %}
                <li class="next"></li>
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                            Next <span aria-hidden="true">→</span></a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

{% endblock %}

part_2 (Django)/quotes/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<p>Don't have an account? <a href="{% url 'users:signup' %}">Sign up</a></p>
{% endblock %}

part_2 (Django)/quotes/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>
<p>Already have an account? <a href="{% url 'users:login' %}">Log in</a></p>
{% endblock %}

part_2 (Django)/users/templates/users/author_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span> <span
            class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>
{% endblock %}

part_2 (Django)/users/templates/users/password_reset_form.html
{% extends "base.html" %}

{% block content %}
<h2>Reset Password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset</button>
</form>
{% endblock %}